import * as statics from './options.statics.controller'
import { Router } from 'express'

const router = new Router()

router.get('/options/asqResults', statics.readAsqResults)
router.get('/options/carefuls', statics.readCarefuls)
router.get('/options/civilStatuses', statics.readCivilStatuses)
router.get('/options/courages', statics.readCourages)
router.get('/options/doctors', statics.readDoctors)
router.get('/options/dreams', statics.readDreams)
router.get('/options/economicals', statics.readEconomicals)
router.get('/options/evaluations', statics.readEvaluations)
router.get('/options/feelings', statics.readFeelings)
router.get('/options/asqfoods', statics.readFoods)
router.get('/options/frustrations', statics.readFrustrations)
router.get('/options/idiResults', statics.readIdiResults)
router.get('/options/ifdResults', statics.readIfdResults)
router.get('/options/interests', statics.readInterests)
router.get('/options/interpersonals', statics.readInterpersonals)
router.get('/options/interviews', statics.readInterviews)
router.get('/options/lesions', statics.readLesions)
router.get('/options/levelEstudies', statics.readLevelEstudies)
router.get('/options/mchatResults', statics.readMchatResults)
router.get('/options/participations', statics.readParticipations)
router.get('/options/prevalences', statics.readPrevalences)
router.get('/options/relationships', statics.readRelationships)
router.get('/options/religions', statics.readReligions)
router.get('/options/rols', statics.readRols)
router.get('/options/statusEvaluations', statics.readStatusEvaluations)
router.get('/options/statusRelationships', statics.readStatusRelationships)
router.get('/options/contacts', statics.readContacts)
router.get('/options/situations', statics.readSituations)
router.get('/options/grades', statics.readGrades)
router.get('/options/activities', statics.readActivities)
router.get('/options/academicLevels', statics.readAcademicLevels)
router.get('/options/asqOptions', statics.readAsqOptions)
router.get('/options/asqSeOptions', statics.readAsqSeOptions)

export default router
