# Specify a base image
FROM node:lts-alpine

# Set Working Directory 
WORKDIR '/app'

# Copy only package.json and yarn.lock for cache
COPY package.json yarn.lock ./

# Install some depenendencies
RUN yarn install --frozen-lockfile

# Copies everything over to Docker environment
COPY . .

# Finally runs the application
CMD [ "yarn", "run", "test" ]
